// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Starving {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Starving.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        internal static string FacebookLoginFail {
            get {
                return ResourceManager.GetString("FacebookLoginFail", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string CreateReview {
            get {
                return ResourceManager.GetString("CreateReview", resourceCulture);
            }
        }
        
        internal static string HaveBeenInThisPlace {
            get {
                return ResourceManager.GetString("HaveBeenInThisPlace", resourceCulture);
            }
        }
        
        internal static string ShareReview {
            get {
                return ResourceManager.GetString("ShareReview", resourceCulture);
            }
        }
        
        internal static string EnableGPS {
            get {
                return ResourceManager.GetString("EnableGPS", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string SeeLikes {
            get {
                return ResourceManager.GetString("SeeLikes", resourceCulture);
            }
        }
        
        internal static string UsersWhoLikes {
            get {
                return ResourceManager.GetString("UsersWhoLikes", resourceCulture);
            }
        }
        
        internal static string NoReviews {
            get {
                return ResourceManager.GetString("NoReviews", resourceCulture);
            }
        }
        
        internal static string RetrievingReviews {
            get {
                return ResourceManager.GetString("RetrievingReviews", resourceCulture);
            }
        }
        
        internal static string ReviewFieldEmpty {
            get {
                return ResourceManager.GetString("ReviewFieldEmpty", resourceCulture);
            }
        }
        
        internal static string RetrievingLikes {
            get {
                return ResourceManager.GetString("RetrievingLikes", resourceCulture);
            }
        }
        
        internal static string NoLikesToShow {
            get {
                return ResourceManager.GetString("NoLikesToShow", resourceCulture);
            }
        }
        
        internal static string NoPlacesToShow {
            get {
                return ResourceManager.GetString("NoPlacesToShow", resourceCulture);
            }
        }
        
        internal static string RetrievingPlaces {
            get {
                return ResourceManager.GetString("RetrievingPlaces", resourceCulture);
            }
        }
        
        internal static string LikePlaces {
            get {
                return ResourceManager.GetString("LikePlaces", resourceCulture);
            }
        }
        
        internal static string DislikePlaces {
            get {
                return ResourceManager.GetString("DislikePlaces", resourceCulture);
            }
        }
        
        internal static string PlacesListHeader {
            get {
                return ResourceManager.GetString("PlacesListHeader", resourceCulture);
            }
        }
        
        internal static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        internal static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        internal static string Liked {
            get {
                return ResourceManager.GetString("Liked", resourceCulture);
            }
        }
        
        internal static string TakeMeThere {
            get {
                return ResourceManager.GetString("TakeMeThere", resourceCulture);
            }
        }
        
        internal static string MyLatestReviews {
            get {
                return ResourceManager.GetString("MyLatestReviews", resourceCulture);
            }
        }
        
        internal static string SearchPlaces {
            get {
                return ResourceManager.GetString("SearchPlaces", resourceCulture);
            }
        }
        
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
    }
}
